# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1095554ac5a8c852cc586b63ab69ad8bb16177f16a807310d654731104d2e3349dc9d20e88d077636d29dda92c4705695961fa8b0aa5292f75501fe09dad1e76

test:
  secret_key_base: 89de19bd160981f004c89d41202215af792644a2defa54edb6b6ef473021e137461f364161a406f9dc13a3aa4726563aa42ab7c85f075b7ce8397c1cfc22aeec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
